#!/usr/bin/env zsh
#
# contextual-history-fzf.zsh
#
# fzf integration for the contextual-history plugin. Provides:
#   - contextual-history-fzf-widget: a stand-alone Ctrl-R-style widget
#     that surfaces zsh's HIST_FOREIGN bit (visible as the `*` column
#     in `fc -l`), letting the user filter between "local" (entries
#     this shell wrote) and "all" (every entry in the ring) without
#     leaving fzf.
#   - Auto-detection of fzf's fzf-history-widget at first precmd, with
#     optional ^R takeover (off by default).
#
# Source order: this file expects the main plugin (contextual-history.zsh)
# to have already loaded. The main plugin sources us automatically at
# the end of its own load; users who want to control loading explicitly
# can source us themselves AFTER the main plugin.
#
# Hard dependencies (must be defined when this file is sourced):
#   _ch_resolve, _ch_dbg                        - from main plugin
#   _context_history_have_native_fast_refresh   - from main plugin
#   _context-history-wrap-widget         - from widgets sibling
#   CONTEXTUAL_HISTORY_WRAP_WIDGETS             - from widgets sibling
#   CONTEXTUAL_HISTORY_REFRESHING_WIDGETS       - from widgets sibling
#   add-zsh-hook                                - autoloaded by main plugin
#
# The main plugin auto-sources the widgets sibling first, so the
# above are all available by the time this file loads.

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------
#
# Resolved via the same env > zstyle > default precedence the main
# plugin uses. The fzf widget itself is registered unconditionally;
# user-visible activation requires either an explicit `bindkey` or
# fzf-bind-ctrl-r=true (with fzf loaded at first precmd).

_ch_resolve CONTEXTUAL_HISTORY_FZF_BIND_CTRL_R   fzf-bind-ctrl-r      false
_ch_resolve CONTEXTUAL_HISTORY_FZF_VIEW          fzf-default-view     all
_ch_resolve CONTEXTUAL_HISTORY_FZF_LOCAL_KEY     fzf-toggle-local-key 'alt-l'
_ch_resolve CONTEXTUAL_HISTORY_FZF_ALL_KEY       fzf-toggle-all-key   'alt-a'
_ch_resolve CONTEXTUAL_HISTORY_FZF_PROMPT_LOCAL  fzf-prompt-local     'LOCAL> '
_ch_resolve CONTEXTUAL_HISTORY_FZF_PROMPT_ALL    fzf-prompt-all       'ALL> '
_ch_resolve CONTEXTUAL_HISTORY_FZF_EXTRA_OPTS    fzf-extra-opts       ''

#-------------------------------------------------------------------------------
# Toggle helper (POSIX-sh script on disk)
#-------------------------------------------------------------------------------
#
# fzf's transform-query binds invoke an external command and replace
# the query with that command's stdout. We need a way to manipulate
# the current query (strip / re-prepend a flag-anchor token) from
# fzf's subprocess context. A small POSIX-sh script on a stable cache
# path is the cleanest option:
#   - One file shared by every shell using this plugin.
#   - Idempotent regeneration (rewrite only when content drifts).
#   - No re-sourcing the plugin in the subshell, no $SHELL-specific
#     quoting acrobatics inside the --bind expression.

function _context-history-fzf-ensure-toggle-helper() {
  local cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/contextual-history
  mkdir -p "$cache_dir" 2>/dev/null
  _context_history_fzf_toggle_helper="$cache_dir/fzf-toggle.sh"
  # The flag anchor is `^L ` (caret-L-space) so it matches against
  # fzf's space-joined --with-nth display of the flag column plus
  # the text column.
  local want='#!/bin/sh
# Auto-generated by zsh-contextual-history. Do not edit; will be overwritten.
# Args: <local|all> [query tokens...]
view=$1
shift
q="$*"
# Strip a leading flag-anchor token if present. Patterns try
# longest-first so a trailing-space anchor strips cleanly.
case "$q" in
  "^L "*)  q="${q#"^L "}" ;;
  "^L"*)   q="${q#"^L"}" ;;
  "!^F "*) q="${q#"!^F "}" ;;
  "!^F"*)  q="${q#"!^F"}" ;;
esac
case "$view" in
  local) printf "%s\\n" "^L $q" ;;
  all)   printf "%s\\n" "$q" ;;
esac
'
  if [[ ! -f $_context_history_fzf_toggle_helper ]] \
     || [[ "$(cat $_context_history_fzf_toggle_helper 2>/dev/null)" != "$want" ]]; then
    print -r -- "$want" > "$_context_history_fzf_toggle_helper"
    chmod +x "$_context_history_fzf_toggle_helper" 2>/dev/null
  fi
}

#-------------------------------------------------------------------------------
# L/F classification basis
#-------------------------------------------------------------------------------
#
# The snapshot below classifies ring entries L (this shell typed) vs
# F (anything else) by looking each entry's "${stim}:${text}" up in
# the main plugin's `_context_history_local_writes` associative set,
# which the addhistory hook populates on every command. See the main
# plugin's "Tracking sets" block for the full discussion. The widget
# trusts that set as the source of truth for L/F.

#-------------------------------------------------------------------------------
# Tmux awareness
#-------------------------------------------------------------------------------
#
# Mirror of fzf upstream's __fzfcmd: when running inside tmux AND the
# user has opted in to tmux popups (FZF_TMUX=1 or FZF_TMUX_OPTS set),
# invoke fzf-tmux instead of plain fzf. The returned string is meant
# to be eval'd or used in `$(...)` substitution; the trailing `-- ` on
# the fzf-tmux branch lets the caller append `"$@"`-style args.

function _context-history-fzf-cmd() {
  if [[ -n ${TMUX_PANE-} ]] \
     && { [[ "${FZF_TMUX:-0}" != 0 ]] || [[ -n ${FZF_TMUX_OPTS-} ]] }; then
    print -r -- "fzf-tmux ${FZF_TMUX_OPTS:--d${FZF_TMUX_HEIGHT:-40%}} -- "
  else
    print -r -- "fzf"
  fi
}

#-------------------------------------------------------------------------------
# Snapshot builder
#-------------------------------------------------------------------------------
#
# Reads `fc -lirt '%s' 1` (newest-first, Unix-epoch timestamp column)
# and emits one NUL-terminated tab-delimited record per history
# entry:
#   <flag>\t<histnum>\t<stim>\t<text>\0
# where <flag> is L (this shell typed it) or F (everything else).
#
# Why fc -lirt '%s':
#   - `-l` lists with histnum + `*` foreign marker.
#   - `-i` would give ISO date/time; `-t '%s'` gives Unix epoch
#     seconds directly, which is what we use to look up
#     `_context_history_local_writes`. fc honours custom strftime
#     format strings (builtin.c:1788 sets tdfmt = OPT_ARG(ops,'t')).
#   - `-r` reverses order so the newest entry appears first in the
#     stream. Combined with fzf's `--scheme=history --tiebreak=index`
#     this puts the most-recent command at the top of the picker —
#     matching fzf-history-widget upstream (which uses `fc -rl`).
#
# L/F classification: each entry's "${stim}:${text}" is looked up in
# `_context_history_local_writes`, which is populated at every
# zshaddhistory hook firing in the main plugin. Survives ring
# replacement (toggle, chpwd) because the lookup key is on-disk
# identity, not histnum.
#
# Multi-line entries: zsh history can contain literal newlines (e.g.
# multi-line for-loops). fc -l prints continuation lines with no
# leading histnum/timestamp prefix; we re-attach them to the prior
# record and pass --read0 to fzf so embedded newlines don't split
# records. The text used for the lookup includes the embedded
# newlines, matching the chline the addhistory hook saw.

function _context-history-fzf-build-snapshot() {
  emulate -L zsh
  setopt extended_glob

  local line
  local -a fc_lines
  fc_lines=("${(@f)$(fc -lirt '%s' 1 2>/dev/null)}")

  # Buffer the parsed parts of the current entry. We hold off
  # emitting until we hit the next entry's header (or end of input)
  # so we can fold any multi-line continuation into the text and
  # do the L/F lookup against the COMPLETE entry text.
  local prev_histnum="" prev_stim="" prev_text=""

  emit_prev() {
    [[ -z $prev_histnum ]] && return 0
    local flag=F
    (( ${+_context_history_local_writes[${prev_stim}:${prev_text}]} )) && flag=L
    printf '%s\0' "${flag}"$'\t'"${prev_histnum}"$'\t'"${prev_stim}"$'\t'"${prev_text}"
  }

  for line in "${fc_lines[@]}"; do
    # Header: optional leading spaces, histnum, [space|*], space,
    # epoch-seconds, two spaces, first text line.
    if [[ $line == (#b)[[:space:]]#(<->)([[:space:]]|\*)[[:space:]](<->)[[:space:]][[:space:]](*) ]]; then
      emit_prev
      prev_histnum=${match[1]}
      prev_stim=${match[3]}
      prev_text=${match[4]}
      # match[2] (the `*`/space marker) is intentionally unused -
      # we don't trust zsh's HIST_FOREIGN as a self-vs-peer signal
      # (see the comment block above on why).
    else
      # Continuation line of a multi-line history entry.
      prev_text+=$'\n'"$line"
    fi
  done
  emit_prev
}

#-------------------------------------------------------------------------------
# The widget
#-------------------------------------------------------------------------------
#
# Why not just wrap fzf-history-widget?
#   - fzf's perl path reads `${(kv)history[@]}` which carries no
#     foreign-bit at all (zsh/parameter doesn't expose it).
#   - fzf's awk fallback parses `fc -rl 1` but strips the `*` column
#     in its display regex.
# Both paths are blind to the local/foreign distinction by design;
# a wrap could refresh state before fzf reads but can't change what
# fzf reads.
#
# Filter mechanism: the snapshot's flag column is in field 1.
# --with-nth=1,4.. joins fields 1 and 4+ with a single space for both
# display and search target ("L echo hello" or "F ls -la"). fzf's
# extended-search anchor `^L ` filters in the local-only direction
# without us needing a separate input source. Two binds use
# transform-query to flip the view by manipulating the query - no
# `reload`, no subprocess fork per toggle, and the user's free-text
# query is preserved across flips.
#
# Snapshot is fixed for the duration of an fzf session. HIST_FOREIGN
# exists only in the live shell's in-memory ring, so a subprocess
# can't recompute it. Close fzf and re-press the bind to refresh
# against new peer-shell writes.

function contextual-history-fzf-widget() {
  emulate -L zsh
  setopt localoptions pipefail no_aliases no_glob no_sh_glob extendedglob

  if ! (( ${+commands[fzf]} )); then
    zle -M "contextual-history-fzf-widget: fzf not on PATH"
    return 1
  fi

  # Refresh the ring against on-disk state so peer shells' writes show
  # up. Uses the native fast-refresh builtin when available (preserves
  # HIST_FOREIGN); otherwise falls back to `fc -RI` and accepts that
  # foreignness is laundered (everything will appear as local).
  if [[ ${_context_history_have_native_fast_refresh:-false} == true ]]; then
    contextual-history-fast-refresh "$HISTFILE" 2>/dev/null
  else
    fc -RI "$HISTFILE" 2>/dev/null
  fi

  # Initial query expression based on the configured default view.
  # The `^L ` anchor matches the space-joined flag+text display
  # produced by --with-nth=1,4.. (fzf joins selected fields with a
  # single space when building the search target).
  local initial_query=""
  local initial_prompt="${CONTEXTUAL_HISTORY_FZF_PROMPT_ALL}"
  case ${CONTEXTUAL_HISTORY_FZF_VIEW:-all} in
    local)
      initial_query="^L ${LBUFFER}"
      initial_prompt="${CONTEXTUAL_HISTORY_FZF_PROMPT_LOCAL}"
      ;;
    *)
      initial_query="${LBUFFER}"
      ;;
  esac

  _context-history-fzf-ensure-toggle-helper
  local helper=$_context_history_fzf_toggle_helper

  local local_key=${CONTEXTUAL_HISTORY_FZF_LOCAL_KEY:-alt-l}
  local all_key=${CONTEXTUAL_HISTORY_FZF_ALL_KEY:-alt-a}
  local prompt_local=${CONTEXTUAL_HISTORY_FZF_PROMPT_LOCAL:-'LOCAL> '}
  local prompt_all=${CONTEXTUAL_HISTORY_FZF_PROMPT_ALL:-'ALL> '}

  # --with-nth=1,4.. shows the flag column (column 1) joined with the
  # text column (column 4 onward), space-separated by fzf. The histnum
  # and stim columns are hidden but remain in the record for our own
  # post-selection parsing. No --nth: fzf searches the entire
  # post-rewrite display, so `^L ` and the user's free-text query
  # match against the same target naturally.
  #
  # --multi mirrors upstream fzf-history-widget: tab-marks accumulate
  # and the retrieval loop below joins them with newlines.
  # --highlight-line + --wrap-sign match upstream's display polish.
  local -a fzf_args
  fzf_args=(
    --read0
    --delimiter=$'\t'
    --with-nth=1,4..
    --scheme=history
    --tiebreak=index
    --multi
    --highlight-line
    --wrap-sign $'\t↳ '
    --query="${initial_query}"
    --prompt="${initial_prompt}"
    --bind="${local_key}:transform-query(${helper} local {q})+transform-prompt(echo ${(q)prompt_local})"
    --bind="${all_key}:transform-query(${helper} all {q})+transform-prompt(echo ${(q)prompt_all})"
    --bind='ctrl-r:toggle-sort'
    --header="${local_key}=local  ${all_key}=all  tab=multi"
  )

  # Honour upstream's FZF_CTRL_R_OPTS for backwards compat with users
  # who already customize fzf's ^R search. Applied before our local
  # extras so the latter still win on conflicts.
  if [[ -n ${FZF_CTRL_R_OPTS-} ]]; then
    fzf_args+=(${(z)FZF_CTRL_R_OPTS})
  fi
  if [[ -n $CONTEXTUAL_HISTORY_FZF_EXTRA_OPTS ]]; then
    fzf_args+=(${(z)CONTEXTUAL_HISTORY_FZF_EXTRA_OPTS})
  fi

  # _context-history-fzf-cmd emits either "fzf" or "fzf-tmux ... -- ".
  # Word-split via (z) so the trailing `-- ` becomes its own array
  # element when fzf-tmux is in play; trailing args attach cleanly
  # either way.
  local -a fzf_cmd
  fzf_cmd=(${(z)"$(_context-history-fzf-cmd)"})

  local selected
  selected=$(_context-history-fzf-build-snapshot | "${fzf_cmd[@]}" "${fzf_args[@]}")
  local ret=$?

  if (( ret != 0 )) || [[ -z $selected ]]; then
    zle reset-prompt
    return $ret
  fi

  # Selected output is one record per picked entry, joined by newlines.
  # Each record may itself span multiple lines (multi-line history
  # entries kept intact via --read0). The structure looks like:
  #
  #   L\t<histnum>\t<stim>\t<line 1 of text>
  #   <line 2 of text>
  #   ...
  #   L\t<histnum2>\t<stim2>\t<line 1 of next picked entry>
  #
  # We split by newline, filter for lines starting with the flag-tab-
  # histnum-tab pattern, retrieve each via vi-fetch-history, and join
  # the fetched commands with newlines into BUFFER. Continuation
  # lines don't match the filter and are skipped (the histnum-keyed
  # fetch gets the whole multi-line entry anyway).
  local -a cmds
  local -a mbegin mend match
  local line histnum
  local matched_any=0
  for line in ${(ps:\n:)selected}; do
    if [[ $line == (#b)[LF]$'\t'(<->)$'\t'<->$'\t'* ]]; then
      matched_any=1
      histnum=${match[1]}
      # vi-fetch-history fetches the entry by event number into BUFFER
      # without relying on the $history assoc array (which has a known
      # lag bug on foreign entries -
      # https://zsh.org/mla/users/2024/msg00692.html).
      zle .push-line
      zle vi-fetch-history -n $histnum
      if (( ${#BUFFER} )); then
        cmds+=("$BUFFER")
      fi
      BUFFER=""
      zle .get-line
    fi
  done

  if (( matched_any )); then
    if (( ${#cmds[@]} )); then
      # Strip trailing newlines from each fetched command, then join
      # them with newlines. Matches upstream's expansion exactly.
      BUFFER="${(pj:\n:)${(@)cmds%%$'\n'#}}"
      CURSOR=${#BUFFER}
    fi
  else
    # No histnum line matched - the user typed an arbitrary query
    # into the picker and hit Enter without selecting. Stuff the raw
    # output into LBUFFER (upstream parity).
    LBUFFER="$selected"
  fi

  zle reset-prompt
  return 0
}
zle -N contextual-history-fzf-widget

#-------------------------------------------------------------------------------
# Detect fzf, optionally take over ^R, wrap for refresh
#-------------------------------------------------------------------------------
#
# Detection happens at first precmd because plugin load order is not
# under our control - fzf's key-bindings.zsh may have been sourced
# before us or via zsh-defer afterward. We re-check on every precmd
# until we've either taken over (when configured) or determined fzf
# isn't going to load this session.

typeset -g _context_history_fzf_detected=false

function _context-history-fzf-maybe-takeover() {
  [[ $_context_history_fzf_detected == true ]] && return 0
  (( ${+widgets[fzf-history-widget]} )) || return 0
  _context_history_fzf_detected=true

  # Wrap fzf-history-widget so the mtime-gated refresh fires before
  # fzf reads. Our own widget already calls refresh internally; wrap
  # it too for consistency.
  if [[ $CONTEXTUAL_HISTORY_WRAP_WIDGETS == true ]]; then
    local extra
    for extra in fzf-history-widget contextual-history-fzf-widget; do
      if (( ${CONTEXTUAL_HISTORY_REFRESHING_WIDGETS[(I)$extra]} == 0 )); then
        CONTEXTUAL_HISTORY_REFRESHING_WIDGETS+=("$extra")
      fi
    done
    _context-history-wrap-widget
  fi

  if [[ ${CONTEXTUAL_HISTORY_FZF_BIND_CTRL_R:-false} == true ]]; then
    _ch_dbg "fzf-bind-ctrl-r: binding ^R to contextual-history-fzf-widget"
    bindkey -M emacs '^R' contextual-history-fzf-widget
    bindkey -M viins '^R' contextual-history-fzf-widget
    bindkey -M vicmd '^R' contextual-history-fzf-widget
  fi
}

add-zsh-hook precmd _context-history-fzf-maybe-takeover
