/*
 * contextual_history.c - native helper module for the contextual-history zsh plugin.
 *
 * Provides three builtins:
 *
 *   contextual-history-tee <file> <command>
 *     Append one command line to <file> in extended-history format while
 *     holding zsh's own lockhistfile lock. Lock protocol (HIST_FCNTL_LOCK
 *     on/off) is picked up automatically because we call zsh's
 *     lockhistfile()/unlockhistfile() directly.
 *
 *   contextual-history-replace-ring <file>
 *     Wipe the in-memory history ring and reload it cleanly from <file>.
 *     This is the leak-free alternative to the plugin's pure-shell
 *     `HISTSIZE=2; fc -R` ring-replace dance, which leaks 2 entries from
 *     the previous context (zsh's histsiz minimum is 2). Walks
 *     hist_ring + freehistnode for every entry, resets curhist /
 *     histlinect, then calls readhistfile().
 *
 *   contextual-history-fast-refresh <file>
 *     Incremental merge from <file> with HFILE_FAST semantics - same
 *     readflags zsh's own SHARE_HISTORY hend-merge uses
 *     (HFILE_USE_OPTIONS | HFILE_FAST). Entries newly loaded get
 *     HIST_FOREIGN, making `fc -l`'s `*` column meaningful for entries
 *     pulled in by widget-time refreshes. The pure-shell fallback
 *     (`fc -RI`) uses HFILE_SKIPOLD, which does NOT set HIST_FOREIGN
 *     and so launders the local/foreign distinction. Used by the
 *     refresh-on-nav hook and the fzf widget to preserve foreignness
 *     between hend merges.
 *
 * Module name (zsh side): `zsh/contextual_history`. The plugin loads via:
 *     zmodload zsh/contextual_history
 *
 * Builds against an unpacked & ./configure'd zsh source tree. We
 * deliberately do NOT include zsh's `zsh.mdh`, which would also pull in
 * dozens of .epro files (function-prototype tables generated during a
 * full zsh `make`). That would force users to run a complete zsh build
 * just to compile this module. Instead we include the few committed-in-
 * tarball headers we need (zsh_system.h, zsh.h) and manually
 * `extern`-declare the zsh functions we call.
 */

/* Headers from the configured zsh source tree.
 * `config.h` is generated by ./configure. The rest are checked into the
 * source tarball. */
#include "config.h"
#include "zsh_system.h"
#include "zsh.h"

/* Function prototypes from zsh that we use. Normally these come from
 * generated .epro files (hist.epro, utils.epro, module.epro) included via
 * zsh.mdh - we declare them by hand to avoid the .epro dependency.
 *
 * For replace-ring we need the ring-management primitives:
 *   freehistnode    - free an entry, unlink from histlist + histtab
 *   readhistfile    - load events into ring from file
 *   unlinkcurline   - detach the curline placeholder from the ring
 *   linkcurline     - reattach curline (bumps curhist, sets curline.histnum)
 * And the globals: hist_ring (head pointer), curhist, histlinect, curline. */
extern int   lockhistfile(char *fn, int keep_trying);
extern void  unlockhistfile(char *fn);
extern char *unmeta(const char *file_name);
extern void  zwarnnam(const char *cmd, const char *fmt, ...);
extern char **featuresarray(Module m, Features f);
extern int   handlefeatures(Module m, Features f, int **enables);
extern int   setfeatureenables(Module m, Features f, int *e);
extern void  freehistnode(HashNode nodeptr);
extern void  readhistfile(char *fn, int err, int readflags);

/* Globals from zsh's hist.c. zlong is zsh's history-counter type. */
extern Histent        hist_ring;
extern zlong          curhist;
extern zlong          histlinect;
extern struct histent curline;

/*
 * unlinkcurline / linkcurline are STATIC in zsh's hist.c (Src/hist.c
 * line 1071, 1085) so we can't call them via the dynamic-lookup path
 * that works for the public history functions. We reimplement them
 * inline to match zsh's behavior exactly. Source-of-truth is hist.c
 * - when bumping zsh source-tree version, double-check these still
 * mirror the originals.
 */
static void _ch_unlinkcurline(void) {
    curline.up->down = curline.down;
    curline.down->up = curline.up;
    if (hist_ring == &curline) {
        if (!histlinect)
            hist_ring = NULL;
        else
            hist_ring = curline.up;
    }
    curhist--;
}

static void _ch_linkcurline(void) {
    if (!hist_ring) {
        hist_ring = curline.up = curline.down = &curline;
    } else {
        curline.up = hist_ring;
        curline.down = hist_ring->down;
        hist_ring->down = hist_ring->down->up = &curline;
        hist_ring = &curline;
    }
    curline.histnum = ++curhist;
}

#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <unistd.h>
#include <stdio.h>

/*
 * contextual-history-tee <histfile> <command-text>
 *
 * Append a single extended-history-format line to <histfile> while holding
 * zsh's own lockhistfile lock.
 *
 * We deliberately do NOT call savehistfile() because:
 *   - savehistfile iterates the calling shell's hist_ring, but the command
 *     we're tee'ing isn't yet in hist_ring at zshaddhistory time (it gets
 *     added in hend(), Src/hist.c around line 1602).
 *   - We're writing to a file that is NOT this shell's $HISTFILE; a
 *     savehistfile() with HFILE_USE_OPTIONS would update lasthist with
 *     values for the inactive file, corrupting our active-file tracking.
 *
 * Instead: lockhistfile -> open(O_APPEND) -> fprintf one line -> close ->
 * unlockhistfile. Single-syscall write of one line is kernel-atomic with
 * O_APPEND, and the held lock serialises us against stock zsh's SHARE/INC
 * writers on the same file.
 */
static int
bin_contextual_history_tee(char *nam, char **argv, UNUSED(Options ops), UNUSED(int func))
{
    char *file = argv[0];
    char *cmd  = argv[1];

    if (!file || !cmd) {
        zwarnnam(nam, "usage: contextual-history-tee <file> <command>");
        return 1;
    }

    /* keep_trying=1 means retry up to ~10s per zsh's internal timeout.
     * Returns 0 on success, 1 on temporary failure, 2 on permanent. */
    int rc = lockhistfile(file, 1);
    if (rc != 0) {
        zwarnnam(nam, "lock failed for %s (rc=%d)", file, rc);
        return 1;
    }

    char *unmeta_file = unmeta(file);
    int fd = open(unmeta_file, O_CREAT | O_WRONLY | O_APPEND | O_NOCTTY, 0600);
    int ret = 1;
    if (fd >= 0) {
        FILE *out = fdopen(fd, "a");
        if (out) {
            time_t now = time(NULL);
            /* Extended-history format: `: <stim>:<elapsed>;<text>\n`.
             * Elapsed=0 because zshaddhistory fires before exec. */
            if (fprintf(out, ": %ld:0;%s\n", (long)now, cmd) > 0)
                ret = 0;
            fclose(out);
        } else {
            close(fd);
        }
    } else {
        zwarnnam(nam, "open failed for %s: %e", file, errno);
    }

    unlockhistfile(file);
    return ret;
}

/*
 * contextual-history-replace-ring <file>
 *
 * Clean replace of the in-memory history ring with the contents of
 * <file>. The pure-shell alternative -
 *     HISTSIZE=2; HISTSIZE=$original; fc -R newfile
 * - leaks 2 entries from the previous context because zsh's histsiz
 * clamps at 2 (see test_p11/test_p12 for the documented leak shape).
 * This builtin walks hist_ring directly, freeing every entry, then
 * resets the curhist/histlinect counters and lets readhistfile populate
 * the ring fresh.
 *
 * Sequence:
 *   1. If curline is the head of the ring (which it is during normal
 *      ZLE editing), detach it via unlinkcurline so it isn't touched
 *      by the freehistnode loop.
 *   2. Free every remaining entry. After unlinkcurline, hist_ring
 *      walks through saved entries; freehistnode unlinks the entry
 *      and updates hist_ring as a side effect.
 *   3. Reset curhist=0, histlinect=0 so the new file's events get
 *      sequential histnums starting at 1.
 *   4. Re-attach curline if we detached it (linkcurline bumps
 *      curhist to 1 and sets curline.histnum=1).
 *   5. Acquire the histfile lock and call readhistfile. readhistfile
 *      fires zleentry(ZLE_CMD_SET_HIST_LINE, curhist) at end if
 *      ZLE is active, so histline tracks curhist.
 */
static int
bin_contextual_history_replace_ring(char *nam, char **argv, UNUSED(Options ops), UNUSED(int func))
{
    char *file = argv[0];
    if (!file) {
        zwarnnam(nam, "usage: contextual-history-replace-ring <file>");
        return 1;
    }

    int curline_was_in_ring = (hist_ring == &curline);
    if (curline_was_in_ring)
        _ch_unlinkcurline();

    /* Free all saved entries. freehistnode unlinks from ring +
     * histtab and frees memory; hist_ring and histlinect update as
     * side effects. After the loop, hist_ring is NULL, histlinect=0. */
    while (hist_ring) {
        freehistnode(&hist_ring->node);
    }

    /* Note: we deliberately DO NOT reset curhist. zsh tracks curhist
     * as a monotonically-increasing counter; leaving it where it is
     * matches what `fc -R` does (each new event from the file gets
     * histnum=++curhist). Resetting curhist=0 here confuses zsh's
     * internal lasthist/lockhistfile state in subsequent hend writes
     * - empirically the file at the new $HISTFILE doesn't get
     * created on first write after a curhist=0 reset. histlinect IS
     * 0 already (set by freehistnode loop), which is correct. */

    if (curline_was_in_ring)
        _ch_linkcurline();

    /* readhistfile handles its own locking (lockhistfile when called
     * without HFILE_FAST). */
    readhistfile(file, 0, HFILE_USE_OPTIONS);

    return 0;
}

/*
 * contextual-history-fast-refresh <file>
 *
 * Incremental merge that marks newly loaded entries HIST_FOREIGN.
 * Same readflags as SHARE_HISTORY's hend-merge (Src/hist.c:1518),
 * plus HFILE_SKIPOLD for histtab-based dedup.
 *
 * Why all three flags:
 *   HFILE_FAST       sets HIST_FOREIGN on new loads (the whole point).
 *   HFILE_SKIPOLD    sets HIST_MAKEUNIQUE so duplicates against the
 *                    in-memory ring are dropped before insertion.
 *                    Without it, an out-of-hend invocation against a
 *                    stale lasthist.fpos can re-read entries we
 *                    already have, marking them foreign-as-duplicate.
 *   HFILE_USE_OPTIONS  honours the user's history-option settings.
 *
 * readhistfile manages lockhistfile/unlockhistfile internally.
 * See INTERNALS.md "The native fast-refresh builtin" for the full
 * rationale.
 */
static int
bin_contextual_history_fast_refresh(char *nam, char **argv, UNUSED(Options ops), UNUSED(int func))
{
    char *file = argv[0];
    if (!file) {
        zwarnnam(nam, "usage: contextual-history-fast-refresh <file>");
        return 1;
    }
    readhistfile(file, 0, HFILE_USE_OPTIONS | HFILE_FAST | HFILE_SKIPOLD);
    return 0;
}

/* Builtin descriptor: name, flags, fn, min_args, max_args, func, optstr, defargs. */
static struct builtin bintab[] = {
    BUILTIN("contextual-history-tee",          0, bin_contextual_history_tee,          2, 2, 0, "", NULL),
    BUILTIN("contextual-history-replace-ring", 0, bin_contextual_history_replace_ring, 1, 1, 0, "", NULL),
    BUILTIN("contextual-history-fast-refresh", 0, bin_contextual_history_fast_refresh, 1, 1, 0, "", NULL),
};

static struct features module_features = {
    bintab, sizeof(bintab)/sizeof(*bintab),
    NULL, 0,
    NULL, 0,
    NULL, 0,
    0
};

/* === Module entry points ===
 * Defined twice for compatibility with both SHORTBOOTNAMES=yes (homebrew /
 * macOS, looks up plain `setup_`) and =no (some Linux source builds, looks
 * up `setup_zshQscontextualQuhistory` - the mangled module name with `_`
 * encoded as `Qu` and `/` as `Qs`). The suffixed forms call through to
 * the plain forms so either way zsh finds and invokes us. */

int setup_   (Module m)                    { (void)m; return 0; }
int features_(Module m, char ***features)  { *features = featuresarray(m, &module_features); return 0; }
int enables_ (Module m, int **enables)     { return handlefeatures(m, &module_features, enables); }
int boot_    (Module m)                    { (void)m; return 0; }
int cleanup_ (Module m)                    { return setfeatureenables(m, &module_features, NULL); }
int finish_  (Module m)                    { (void)m; return 0; }

int setup_zshQscontextualQuhistory   (Module m)                    { return setup_(m); }
int features_zshQscontextualQuhistory(Module m, char ***features)  { return features_(m, features); }
int enables_zshQscontextualQuhistory (Module m, int **enables)     { return enables_(m, enables); }
int boot_zshQscontextualQuhistory    (Module m)                    { return boot_(m); }
int cleanup_zshQscontextualQuhistory (Module m)                    { return cleanup_(m); }
int finish_zshQscontextualQuhistory  (Module m)                    { return finish_(m); }
