/*
 * pdh_helper.c - native helper module for the per-directory-history zsh plugin.
 *
 * Provides the `pdh-tee` builtin: appends a single command line to a named
 * history file in zsh's extended-history format, while holding zsh's own
 * history-file lock for the duration of the write. Lock protocol
 * (HIST_FCNTL_LOCK on/off) is picked up automatically because we call
 * lockhistfile() / unlockhistfile() directly.
 *
 * Module name (zsh side): `zsh/pdh`. The plugin loads it via:
 *     zmodload zsh/pdh
 *
 * Builds against an unpacked & ./configure'd zsh source tree. We deliberately
 * do NOT include zsh's `zsh.mdh`, which would also pull in dozens of .epro
 * files (function-prototype tables generated during a full zsh `make`). That
 * would force users to run a complete zsh build just to compile this module.
 * Instead we include the few committed-in-tarball headers we need
 * (zsh_system.h, zsh.h) and manually `extern`-declare the half-dozen zsh
 * functions we call. Result: build needs only `./configure` to have run, no
 * `make`.
 */

/* Headers from the configured zsh source tree.
 * `config.h` is generated by ./configure. The rest are checked into the
 * source tarball. */
#include "config.h"
#include "zsh_system.h"
#include "zsh.h"

/* Function prototypes from zsh that we use. Normally these come from
 * generated .epro files (hist.epro, utils.epro, module.epro) included via
 * zsh.mdh - we declare them by hand to avoid the .epro dependency. */
extern int   lockhistfile(char *fn, int keep_trying);
extern void  unlockhistfile(char *fn);
extern char *unmeta(const char *file_name);
extern void  zwarnnam(const char *cmd, const char *fmt, ...);
extern char **featuresarray(Module m, Features f);
extern int   handlefeatures(Module m, Features f, int **enables);
extern int   setfeatureenables(Module m, Features f, int *e);

#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <unistd.h>
#include <stdio.h>

/*
 * pdh-tee <histfile> <command-text>
 *
 * Append a single extended-history-format line to <histfile> while holding
 * zsh's own lockhistfile lock.
 *
 * We deliberately do NOT call savehistfile() because:
 *   - savehistfile iterates the calling shell's hist_ring, but the command
 *     we're tee'ing isn't yet in hist_ring at zshaddhistory time (it gets
 *     added in hend(), Src/hist.c around line 1602).
 *   - We're writing to a file that is NOT this shell's $HISTFILE; a
 *     savehistfile() with HFILE_USE_OPTIONS would update lasthist with
 *     values for the inactive file, corrupting our active-file tracking.
 *
 * Instead: lockhistfile -> open(O_APPEND) -> fprintf one line -> close ->
 * unlockhistfile. Single-syscall write of one line is kernel-atomic with
 * O_APPEND, and the held lock serialises us against stock zsh's SHARE/INC
 * writers on the same file.
 */
static int
bin_pdh_tee(char *nam, char **argv, UNUSED(Options ops), UNUSED(int func))
{
    char *file = argv[0];
    char *cmd  = argv[1];

    if (!file || !cmd) {
        zwarnnam(nam, "usage: pdh-tee <file> <command>");
        return 1;
    }

    /* keep_trying=1 means retry up to ~10s per zsh's internal timeout.
     * Returns 0 on success, 1 on temporary failure, 2 on permanent. */
    int rc = lockhistfile(file, 1);
    if (rc != 0) {
        zwarnnam(nam, "lock failed for %s (rc=%d)", file, rc);
        return 1;
    }

    char *unmeta_file = unmeta(file);
    int fd = open(unmeta_file, O_CREAT | O_WRONLY | O_APPEND | O_NOCTTY, 0600);
    int ret = 1;
    if (fd >= 0) {
        FILE *out = fdopen(fd, "a");
        if (out) {
            time_t now = time(NULL);
            /* Extended-history format: `: <stim>:<elapsed>;<text>\n`.
             * Elapsed=0 because zshaddhistory fires before exec. */
            if (fprintf(out, ": %ld:0;%s\n", (long)now, cmd) > 0)
                ret = 0;
            fclose(out);
        } else {
            close(fd);
        }
    } else {
        zwarnnam(nam, "open failed for %s: %e", file, errno);
    }

    unlockhistfile(file);
    return ret;
}

/* Builtin descriptor: name, flags, fn, min_args, max_args, func, optstr, defargs. */
static struct builtin bintab[] = {
    BUILTIN("pdh-tee", 0, bin_pdh_tee, 2, 2, 0, "", NULL),
};

static struct features module_features = {
    bintab, sizeof(bintab)/sizeof(*bintab),
    NULL, 0,
    NULL, 0,
    NULL, 0,
    0
};

/* === Module entry points ===
 * Defined twice for compatibility with both SHORTBOOTNAMES=yes (homebrew /
 * macOS, looks up plain `setup_`) and =no (some Linux source builds, looks
 * up `setup_zshQspdh`). The suffixed forms call through to the plain forms
 * - either way zsh finds and invokes us. */

int setup_   (Module m)                    { (void)m; return 0; }
int features_(Module m, char ***features)  { *features = featuresarray(m, &module_features); return 0; }
int enables_ (Module m, int **enables)     { return handlefeatures(m, &module_features, enables); }
int boot_    (Module m)                    { (void)m; return 0; }
int cleanup_ (Module m)                    { return setfeatureenables(m, &module_features, NULL); }
int finish_  (Module m)                    { (void)m; return 0; }

int setup_zshQspdh   (Module m)                    { return setup_(m); }
int features_zshQspdh(Module m, char ***features)  { return features_(m, features); }
int enables_zshQspdh (Module m, int **enables)     { return enables_(m, enables); }
int boot_zshQspdh    (Module m)                    { return boot_(m); }
int cleanup_zshQspdh (Module m)                    { return cleanup_(m); }
int finish_zshQspdh  (Module m)                    { return finish_(m); }
