#!/usr/bin/env zsh
# test_p27_fzf_filter_toggle
#
# End-to-end test of the fzf widget's filter mechanism. Two SHARE
# shells share a context; shell B writes commands; shell A pulls them
# via SHARE merge AND via the plugin's fast-refresh; shell A then
# builds the fzf snapshot and exercises both filter expressions via
# `fzf --filter` (non-interactive). Verifies:
#
#   1. Local view (`^L `) shows only entries shell A wrote itself.
#   2. All view (empty filter) shows both shell A's and shell B's.
#   3. Toggle helper script idempotently strips and re-applies the
#      flag-anchor token.
#
# Requires the native module (foreign-tagging refresh) AND fzf on
# PATH. Skips otherwise.

source "${0:A:h}/lib/pty_harness.zsh"

PLUGIN_DIR=${0:A:h:h}
MODULE_BUNDLE="$PLUGIN_DIR/module/zsh/contextual_history.bundle"
MODULE_SO="$PLUGIN_DIR/module/zsh/contextual_history.so"

if [[ ! -f $MODULE_BUNDLE && ! -f $MODULE_SO ]]; then
  print -ru2 -- "SKIP ${0:t}: native module not built (run \`cd module && make\`)"
  exit 0
fi

if ! command -v fzf >/dev/null 2>&1; then
  print -ru2 -- "SKIP ${0:t}: fzf not on PATH"
  exit 0
fi

# Locate fzf's directory so we can extend the PTY's minimal PATH.
FZF_DIR=$(dirname "$(command -v fzf)")
HISTROOT=$(mktemp -d -t ch-pty-p27.XXXXXX)
trap "pty_cleanup_all; rm -rf $HISTROOT" EXIT

# TEST_PRE_SOURCE is inlined into the rc generated by the harness;
# we use it to add fzf's bin dir to PATH before the plugin sources
# (no plugin code depends on PATH at source-time but we want it
# available when the test runs fzf via pty_run_cmd).
TEST_PRE_SOURCE="path=(${(q)FZF_DIR} \$path)"

TEST_SHARE_HISTORY=1 CONTEXTUAL_HISTORY_USE_MODULE=true TEST_PRE_SOURCE="$TEST_PRE_SOURCE" \
  pty_spawn shellA "$HISTROOT" || pty_fail "could not spawn shellA"
TEST_SHARE_HISTORY=1 CONTEXTUAL_HISTORY_USE_MODULE=true TEST_PRE_SOURCE="$TEST_PRE_SOURCE" \
  pty_spawn shellB "$HISTROOT" || pty_fail "could not spawn shellB"

# Shell A writes one local command.
pty_run_cmd shellA 'echo aaa-from-A' || pty_fail "shellA cmd"

# Pause to ensure stim ordering distinct from shell B's writes; this
# avoids the same-second lasthist edge case (see test_p26 notes).
sleep 1

# Shell B writes two commands - SHARE_HISTORY appends to the shared
# file at hend; shell A will see them on its next merge.
pty_run_cmd shellB 'echo bbb-from-B-one' || pty_fail "shellB cmd 1"
pty_run_cmd shellB 'echo bbb-from-B-two' || pty_fail "shellB cmd 2"

# Trigger refresh on shell A so HIST_FOREIGN bits land on B's entries.
sleep 0.2
pty_run_cmd shellA "contextual-history-fast-refresh \$HISTFILE; _context-history-fzf-build-snapshot > $HISTROOT/snap-A.raw" \
  || pty_fail "shellA refresh+snapshot"

# Snapshot should contain three command entries: one L (aaa-from-A)
# and two F (bbb-from-B-one, bbb-from-B-two). Plus the most recent
# command (the fast-refresh invocation) is local. Decode and inspect.
print -ru2 -- "--- shellA snapshot (NUL->newline) ---"
tr '\0' '\n' < "$HISTROOT/snap-A.raw" >&2

# Apply the local-view filter via fzf --filter and verify B's entries
# are excluded.
local_out=$(fzf --read0 --delimiter=$'\t' --with-nth=1,4.. --filter='^L ' < "$HISTROOT/snap-A.raw")
print -ru2 -- "--- local filter output ---"
printf '%s\n' "$local_out" >&2

if printf '%s\n' "$local_out" | grep -q 'bbb-from-B'; then
  pty_fail "local-view filter leaked a B-shell entry"
fi
if ! printf '%s\n' "$local_out" | grep -q 'aaa-from-A'; then
  pty_fail "local-view filter missed shell A's own entry"
fi

# All view = no flag filter. Use `^` would also match nothing extra;
# use empty filter (all entries pass).
all_out=$(fzf --read0 --delimiter=$'\t' --with-nth=1,4.. --filter='' < "$HISTROOT/snap-A.raw")
print -ru2 -- "--- all filter output ---"
printf '%s\n' "$all_out" >&2

for needle in 'aaa-from-A' 'bbb-from-B-one' 'bbb-from-B-two'; do
  if ! printf '%s\n' "$all_out" | grep -q "$needle"; then
    pty_fail "all-view filter missing $needle"
  fi
done

# Search-narrowing within local view: only aaa pattern.
narrow_out=$(fzf --read0 --delimiter=$'\t' --with-nth=1,4.. --filter='^L aaa' < "$HISTROOT/snap-A.raw")
print -ru2 -- "--- narrowed local filter ---"
printf '%s\n' "$narrow_out" >&2
if ! printf '%s\n' "$narrow_out" | grep -q 'aaa-from-A'; then
  pty_fail "narrowed local filter missed aaa-from-A"
fi
if printf '%s\n' "$narrow_out" | grep -q 'bbb-from-B'; then
  pty_fail "narrowed local filter included a B-shell entry"
fi

# Toggle helper round-trip. Generate the helper and exercise it
# inline (it's a separate process so we don't need to go through the
# PTY shell).
pty_run_cmd shellA "_context-history-fzf-ensure-toggle-helper; echo HELPER_IS=\$_context_history_fzf_toggle_helper" \
  || pty_fail "could not query helper path"
helper=${REPLY##*HELPER_IS=}
helper=${helper%%$'\r'*}
helper=${helper%%$'\n'*}
[[ -x $helper ]] || pty_fail "helper script not executable: $helper"

# Helper round-trip cases.
[[ "$($helper local 'foo')"          == '^L foo'      ]] || pty_fail "helper local foo"
[[ "$($helper all '^L foo')"         == 'foo'         ]] || pty_fail "helper strip ^L"
[[ "$($helper local '^L already')"   == '^L already'  ]] || pty_fail "helper idempotent local"
[[ "$($helper local '!^F bar')"      == '^L bar'      ]] || pty_fail "helper strip !^F"
[[ "$($helper all '')"               == ''            ]] || pty_fail "helper all empty"

pty_pass
